services:
  postgres:
    image: postgres:16-alpine
    container_name: loukdo-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: loukdo
      POSTGRES_PASSWORD: "112233"
      POSTGRES_DB: loukdo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
